name: CI
on: [push, pull_request]

jobs:
  rake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]
        rails: [5.1.0, 5.2.0, 6.0.0, 6.1.0]
        bundler: [default]
        include:
          - { ruby: "2.4", rails: "4.2", bundler: "1" }
          - { ruby: "2.5", rails: "4.2", bundler: "1" }

    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake

  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.0'
          - '3.2'
          - '3.3'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rspec
